/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gui;

import com.estructuras.EConstantes;
import com.estructuras.Lista;
import com.estructuras.Personaje;
import java.awt.FileDialog;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Walter Mendoza
 */
public class CrearPersonajes extends javax.swing.JFrame {
    private Lista<Personaje> personajes;
    private final int tipo;

    /**
     * Creates new form CrearPersonajes
     * @param personajes
     * @param titulo
     * @param tipo
     */
    public CrearPersonajes(Lista<Personaje> personajes,String titulo, int tipo) {
        initComponents();
        this.setTitle(titulo);
        this.personajes = personajes;
        this.tipo = tipo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblPtsAtaque = new javax.swing.JLabel();
        lblPtsDefensa = new javax.swing.JLabel();
        spAtaque = new javax.swing.JSpinner();
        spDefensa = new javax.swing.JSpinner();
        lblImg = new javax.swing.JLabel();
        txtImg = new javax.swing.JTextField();
        btnImg = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        cbAtaque = new javax.swing.JComboBox();
        lblAtaque = new javax.swing.JLabel();
        jpPersonajes = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Crear Personaje");

        btnAceptar.setText("Aceptar");

        btnCancelar.setText("Cancelar");

        lblNombre.setText("Nombre:");

        lblPtsAtaque.setText("Pts. Ataque");

        lblPtsDefensa.setText("Pts. Defensa");

        spAtaque.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        spDefensa.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        lblImg.setText("Imagen");

        txtImg.setEditable(false);

        btnImg.setText("Selec Imagen");
        btnImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        cbAtaque.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directo", "Disparo" }));

        lblAtaque.setText("Ataque:");

        javax.swing.GroupLayout jpPersonajesLayout = new javax.swing.GroupLayout(jpPersonajes);
        jpPersonajes.setLayout(jpPersonajesLayout);
        jpPersonajesLayout.setHorizontalGroup(
            jpPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        jpPersonajesLayout.setVerticalGroup(
            jpPersonajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPtsAtaque)
                    .addComponent(lblNombre)
                    .addComponent(lblPtsDefensa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAtaque))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(lblImg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImg)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(lblImg)
                    .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(spAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPtsAtaque))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAtaque)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPtsDefensa)))
                    .addComponent(btnAgregar))
                .addGap(30, 30, 30)
                .addComponent(jpPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgActionPerformed
        // TODO add your handling code here:
        try{
            String imgPath;
            FileDialog fd = new FileDialog(this,"Seleccione",FileDialog.LOAD);
            fd.setFile("*.jpeg");
            fd.setVisible(true);
        
            File f = new File(fd.getDirectory(),fd.getFile());
            imgPath=f.toString();
            txtImg.setText(imgPath);
        }catch(NullPointerException  io)
        {
            System.err.println(io);
            JOptionPane.showMessageDialog(this, "No se cargo ninguna imagen", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnImgActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregarPersonajes();
    }//GEN-LAST:event_btnAgregarActionPerformed

   private void agregarPersonajes()
   {
        String nombre = txtNombre.getText();
        String ataque = cbAtaque.getSelectedItem().toString();
        String tipop;
        String img = txtImg.getText();
        int ptsAtk =Integer.parseInt(spAtaque.getValue().toString());
        int ptsDef = Integer.parseInt(spDefensa.getValue().toString());
       
        boolean valido =(nombre.length()>0)&&(img.length()>0)&&(ptsAtk>0)&&(ptsDef>0);
       
        if(tipo == EConstantes.ZOMBIES.getValue()){
            tipop="zombie";
        }else{
            tipop="planta";
        }
        
        if(valido){
            Personaje np = new Personaje(nombre,ataque,tipop,img,ptsAtk,ptsDef);
            personajes.agregar(np);
            PersonajeNuevo a= new PersonajeNuevo(np);
            a.setVisible(true);
            jpPersonajes.add(a);
            jpPersonajes.repaint();
            //jpPersonajes.setVisible(true);
            System.out.println(np);
        }else{
           JOptionPane.showMessageDialog(this, "Faltan Datos", "Errot", JOptionPane.ERROR_MESSAGE);
       }
   }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImg;
    private javax.swing.JComboBox cbAtaque;
    private javax.swing.JDesktopPane jpPersonajes;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPtsAtaque;
    private javax.swing.JLabel lblPtsDefensa;
    private javax.swing.JSpinner spAtaque;
    private javax.swing.JSpinner spDefensa;
    private javax.swing.JTextField txtImg;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
