/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gui;

import com.estructuras.EConstantes;
import com.estructuras.Jugador;

/**
 *
 * @author Walter Mendoza
 */
public class Inicio extends javax.swing.JFrame {

    private Jugador jugador = new Jugador();
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpJugadores = new javax.swing.JLayeredPane();
        btnCPlantas = new javax.swing.JButton();
        btnCZombie = new javax.swing.JButton();
        lpJuego = new javax.swing.JLayeredPane();
        btnIJuego = new javax.swing.JButton();
        btnBDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lpJugadores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Llene los datos de los jugadores:"));

        btnCPlantas.setText("Plantas");
        btnCPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPlantasActionPerformed(evt);
            }
        });

        btnCZombie.setText("Zombie");
        btnCZombie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCZombieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lpJugadoresLayout = new javax.swing.GroupLayout(lpJugadores);
        lpJugadores.setLayout(lpJugadoresLayout);
        lpJugadoresLayout.setHorizontalGroup(
            lpJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpJugadoresLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(lpJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCPlantas)
                    .addComponent(btnCZombie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lpJugadoresLayout.setVerticalGroup(
            lpJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpJugadoresLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(btnCPlantas)
                .addGap(18, 18, 18)
                .addComponent(btnCZombie)
                .addContainerGap())
        );
        lpJugadores.setLayer(btnCPlantas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpJugadores.setLayer(btnCZombie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lpJuego.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 0), new java.awt.Color(204, 204, 204)));

        btnIJuego.setText("Iniciar Juego");
        btnIJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIJuegoActionPerformed(evt);
            }
        });

        btnBDatos.setText("Borrar Datos");

        javax.swing.GroupLayout lpJuegoLayout = new javax.swing.GroupLayout(lpJuego);
        lpJuego.setLayout(lpJuegoLayout);
        lpJuegoLayout.setHorizontalGroup(
            lpJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnBDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lpJuegoLayout.setVerticalGroup(
            lpJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpJuegoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(lpJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIJuego)
                    .addComponent(btnBDatos))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        lpJuego.setLayer(btnIJuego, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpJuego.setLayer(btnBDatos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lpJuego)
                    .addComponent(lpJugadores))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lpJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lpJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPlantasActionPerformed
        // TODO add your handling code here:
        DatosJugador dj = new DatosJugador(this,true,EConstantes.PLANTAS.getValue(),getJugador());
        dj.setVisible(true);
    }//GEN-LAST:event_btnCPlantasActionPerformed

    private void btnCZombieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCZombieActionPerformed
        // TODO add your handling code here:
        DatosJugador dj = new DatosJugador(this,true,EConstantes.ZOMBIES.getValue(),getJugador());
        dj.setVisible(true);
    }//GEN-LAST:event_btnCZombieActionPerformed

    private void btnIJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIJuegoActionPerformed
        // TODO add your handling code here:
        jugador.printDatos();
    }//GEN-LAST:event_btnIJuegoActionPerformed

    public Jugador getJugador()
    {
        return jugador;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBDatos;
    private javax.swing.JButton btnCPlantas;
    private javax.swing.JButton btnCZombie;
    private javax.swing.JButton btnIJuego;
    private javax.swing.JLayeredPane lpJuego;
    private javax.swing.JLayeredPane lpJugadores;
    // End of variables declaration//GEN-END:variables
}
