/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gui;
import com.estructuras.MatrizOrtogonal;

/**
 *
 * @author Walter Mendoza
 */
public final class Tablero extends javax.swing.JFrame {
    private MatrizOrtogonal mo = new MatrizOrtogonal(10,10,this);

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        metodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private final javax.swing.JLabel[][] algo = new javax.swing.JLabel[5][5];
 
    public void metodo(){
        for(int i = 0; i<5;i++)
        {
            for(int j =0;j<5;j++)
            {
                javax.swing.JLabel nueva = new javax.swing.JLabel();
                nueva.setText(""+i+","+j);
                algo[i][j]=nueva;
            }
        }
        
//       this.add(this, 12);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
